services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www/html
    ports:
      - '${APP_PORT:-80}:80'
    depends_on:
      - php-fpm
    networks:
      - mynetwork
    restart: unless-stopped
  php-fpm:
    container_name: weather-app
    build:
      context: ./docker/app
      args:
        PUID: ${WWWUSER}
        PGID: ${WWWGROUP}
        INSTALL_XDEBUG: ${INSTALL_XDEBUG}
    volumes:
      - .:/var/www/html
    user: "1000:1000"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - mynetwork
    depends_on:
        -   mysql
    restart: unless-stopped
  php-scheduler:
    container_name: weather-app-scheduler
    build:
      context: ./docker/app
      args:
        PUID: ${WWWUSER}
        PGID: ${WWWGROUP}
    volumes:
      - .:/var/www/html
    user: "1000:1000"
    networks:
      - mynetwork
    restart: unless-stopped
    command: >
      sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      retries: 3
      timeout: 5s
    restart: unless-stopped
  node:
    build:
      context: ./docker/node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    tty: true
    networks:
      - mynetwork
    ports:
        - "5173:5173"
  mailer:
      image: mailhog/mailhog
      restart: unless-stopped
      ports:
          - "1025:1025"
          - "8082:8025"
      networks:
          - mynetwork
volumes:
  mysql-data:
networks:
  mynetwork:
    driver: bridge
